[RANKER_DATA]
NEG_FRAC = 0.1
RANDOM_STATE = 96

INTERACTIONS_DATA_PATH = "https://drive.google.com/file/d/1hLLRgi9wZ7TVYcUvrJR4bilN6OUfHhKD/view?usp=share_link"
MOVIESMETA_DATA_PATH = "https://drive.google.com/file/d/12R_q0TncwtX9ugE2nUbejIsASU3lS67s/view?usp=share_link"

[CBM_COLS_CONFIG]
ID_COLS = ['user_id', 'movie_id']
DROP_COLS = ['title', 'duration_est']


